FROM docker.tech.beegroup-cimne.com/admin/mr-docker
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y python3 python3-pip openvpn bridge-utils libssl-dev openssl

ADD requirements.txt requirements.txt

RUN pip install -r requirements.txt

USER ubuntu

CMD ["python3"]